"""empty message

Revision ID: f824fad4bbda
Revises: 27ddaab2941b
Create Date: 2022-06-16 23:57:06.681305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f824fad4bbda'
down_revision = '27ddaab2941b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gigs', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gigs', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
