"""empty message

Revision ID: dfd87b3d0fa5
Revises: f824fad4bbda
Create Date: 2022-06-30 22:01:41.788815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd87b3d0fa5'
down_revision = 'f824fad4bbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gigs', sa.Column('image', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gigs', 'image')
    # ### end Alembic commands ###
