"""empty message

Revision ID: 27ddaab2941b
Revises: b18d02bd07e0
Create Date: 2022-06-13 17:15:09.936602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ddaab2941b'
down_revision = 'b18d02bd07e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('deliveryInstructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'deliveryInstructions')
    # ### end Alembic commands ###
